api_platform:
    title: 'sc2.n1.gg'
    description: 'Starcraft 2 data'
    version: '0.1.0'
    show_webby: false
    enable_swagger: false
    enable_swagger_ui: false
    enable_docs: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
