version: "3.7"

networks:
  sc2_api:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.20.0.0/16"

services:

  nginx:
    image: "nginx:1.15"
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.2"

  php:
    build: "./docker/php"
    volumes:
      - "./:/var/www/"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.3"
    user: "${CURRENT_USER}"

  postgres:
    image: "postgres:11.2"
    environment:
      POSTGRES_PASSWORD: "plop"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.4"

  exec:
    build: "./docker/exec"
    volumes:
      - "./:/app"
    user: "${CURRENT_USER}"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.9"

