version: "3.7"

networks:
  sc2_api:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.20.0.0/16"

services:
  nginx:
    image: "nginx:1.15"
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.2"
  php:
    image: "php:7.3-fpm-stretch"
    volumes:
      - "./:/var/www/"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.3"
  postgres:
    image: "postgres:11.2"
    environment:
      POSTGRES_PASSWORD: "plop"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.4"
