version: "3.7"

networks:
  sc2_api:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.20.0.0/16"

services:

  nginx:
    image: "nginx:1.15"
    ports:
      - "80:80"
    depends_on:
      - "php"
    volumes:
      - "./:/var/www/"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
    tmpfs:
      - "/tmp"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.2"

  php:
    build: "./docker/php"
    depends_on:
      - "postgres"
    volumes:
      - "./:/var/www/"
    tmpfs:
      - "/tmp"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.3"
    user: "${CURRENT_USER}"

  postgres:
    image: "postgres:11.2"
    volumes:
      - "./sql/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: "plop"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.4"

  exec:
    build: "./docker/exec"
    depends_on:
      - "nginx"
    volumes:
      - "./:/app"
    networks:
      sc2_api:
        ipv4_address: "172.20.0.9"
    user: "${CURRENT_USER}"

