version: "3.7"
services:
  nginx:
    image: "nginx:1.15"
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - "sc2-api"
  php:
    image: "php:7.3-fpm-stretch"
    volumes:
      - "./:/var/www/"
    networks:
      - "sc2-api"
  postgres:
    image: "postgres:11.2"
    environment:
      POSTGRES_PASSWORD: "plop"
    networks:
      - "sc2-api"

networks:
  sc2-api:
